<?php

namespace Database\Seeders;

use App\Models\EncodeProfile;
use Illuminate\Database\Seeder;

class EncodeProfileSeeder extends Seeder
{
    public function run(): void
    {
        $profiles = [
            // H.264 CPU - Fast profiles
            [
                'name' => '480p FAST (H264)',
                'type' => 'h264_cpu',
                'description' => 'Fast 480p for mobile/web',
                'width' => 854,
                'height' => 480,
                'fps_mode' => 'source',
                'fps' => null,
                'video_bitrate_k' => 800,
                'maxrate_k' => 960,
                'bufsize_k' => 1920,
                'crf' => null,
                'preset' => 'veryfast',
                'profile' => 'main',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 96,
                'audio_channels' => 2,
                'container' => 'mp4',
                'extra_ffmpeg' => null,
                'is_system' => true,
            ],
            [
                'name' => '720p FAST (H264)',
                'type' => 'h264_cpu',
                'description' => 'Fast 720p, good quality/speed balance',
                'width' => 1280,
                'height' => 720,
                'fps_mode' => 'source',
                'fps' => null,
                'video_bitrate_k' => 1500,
                'maxrate_k' => 1800,
                'bufsize_k' => 3600,
                'crf' => null,
                'preset' => 'fast',
                'profile' => 'main',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mp4',
                'extra_ffmpeg' => null,
                'is_system' => true,
            ],
            [
                'name' => '720p BALANCED (H264)',
                'type' => 'h264_cpu',
                'description' => 'Balanced 720p, recommended default',
                'width' => 1280,
                'height' => 720,
                'fps_mode' => 'source',
                'fps' => null,
                'video_bitrate_k' => 2500,
                'maxrate_k' => 3000,
                'bufsize_k' => 6000,
                'crf' => null,
                'preset' => 'medium',
                'profile' => 'high',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mp4',
                'extra_ffmpeg' => null,
                'is_system' => true,
            ],
            [
                'name' => '1080p BALANCED (H264)',
                'type' => 'h264_cpu',
                'description' => '1080p balanced quality/speed',
                'width' => 1920,
                'height' => 1080,
                'fps_mode' => 'source',
                'fps' => null,
                'video_bitrate_k' => 4500,
                'maxrate_k' => 5400,
                'bufsize_k' => 10800,
                'crf' => null,
                'preset' => 'medium',
                'profile' => 'high',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mp4',
                'extra_ffmpeg' => null,
                'is_system' => true,
            ],
            [
                'name' => '1080p HQ (H264)',
                'type' => 'h264_cpu',
                'description' => 'High quality 1080p',
                'width' => 1920,
                'height' => 1080,
                'fps_mode' => 'source',
                'fps' => null,
                'video_bitrate_k' => 6500,
                'maxrate_k' => 7800,
                'bufsize_k' => 15600,
                'crf' => null,
                'preset' => 'slow',
                'profile' => 'high',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mp4',
                'extra_ffmpeg' => null,
                'is_system' => true,
            ],

            // H.265 CPU - Better compression
            [
                'name' => '720p HQ (H265)',
                'type' => 'h265_cpu',
                'description' => '720p with H.265, better compression',
                'width' => 1280,
                'height' => 720,
                'fps_mode' => 'source',
                'fps' => null,
                'video_bitrate_k' => 1500,
                'maxrate_k' => 1800,
                'bufsize_k' => 3600,
                'crf' => null,
                'preset' => 'medium',
                'profile' => 'main',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mp4',
                'extra_ffmpeg' => null,
                'is_system' => true,
            ],
            [
                'name' => '1080p HQ (H265)',
                'type' => 'h265_cpu',
                'description' => '1080p with H.265, excellent compression',
                'width' => 1920,
                'height' => 1080,
                'fps_mode' => 'source',
                'fps' => null,
                'video_bitrate_k' => 3500,
                'maxrate_k' => 4200,
                'bufsize_k' => 8400,
                'crf' => null,
                'preset' => 'medium',
                'profile' => 'main',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mp4',
                'extra_ffmpeg' => null,
                'is_system' => true,
            ],

            // LIVE PROFILES (TS/24-7 streaming)
            [
                'name' => 'LIVE 576p SD',
                'type' => 'h264_cpu',
                'mode' => 'live',
                'description' => 'LIVE 576p SD for 24/7 streaming',
                'width' => 1024,
                'height' => 576,
                'fps_mode' => 'cfr',
                'fps' => 25,
                'video_bitrate_k' => 1500,
                'maxrate_k' => 1500,
                'bufsize_k' => 3000,
                'crf' => null,
                'preset' => 'veryfast',
                'profile' => 'main',
                'pix_fmt' => 'yuv420p',
                'gop' => 50, // 25fps * 2
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mpegts',
                'extra_ffmpeg' => '-ar 48000 -mpegts_flags +resend_headers',
                'is_system' => true,
                'ts_service_name' => 'LIVE 576p',
                'ts_service_provider' => 'IPTV',
                'pcr_period_ms' => 20,
                'pat_period_ms' => 100,
                'pmt_period_ms' => 100,
                'muxrate_k' => 1800,
            ],
            [
                'name' => 'LIVE 720p (Default)',
                'type' => 'h264_cpu',
                'mode' => 'live',
                'description' => 'LIVE 720p default for 24/7 streaming (RECOMMENDED)',
                'width' => 1280,
                'height' => 720,
                'fps_mode' => 'cfr',
                'fps' => 25,
                'video_bitrate_k' => 2500,
                'maxrate_k' => 2500,
                'bufsize_k' => 5000,
                'crf' => null,
                'preset' => 'veryfast',
                'profile' => 'high',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mpegts',
                'extra_ffmpeg' => '-ar 48000 -mpegts_flags +resend_headers',
                'is_system' => true,
                'ts_service_name' => 'LIVE 720p',
                'ts_service_provider' => 'IPTV',
                'pcr_period_ms' => 20,
                'pat_period_ms' => 100,
                'pmt_period_ms' => 100,
                'muxrate_k' => 3000,
            ],
            [
                'name' => 'LIVE 1080p HQ',
                'type' => 'h264_cpu',
                'mode' => 'live',
                'description' => 'LIVE 1080p high quality for 24/7 streaming',
                'width' => 1920,
                'height' => 1080,
                'fps_mode' => 'cfr',
                'fps' => 25,
                'video_bitrate_k' => 5000,
                'maxrate_k' => 5000,
                'bufsize_k' => 10000,
                'crf' => null,
                'preset' => 'fast',
                'profile' => 'high',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 160,
                'audio_channels' => 2,
                'container' => 'mpegts',
                'extra_ffmpeg' => '-ar 48000 -mpegts_flags +resend_headers',
                'is_system' => true,
                'ts_service_name' => 'LIVE 1080p',
                'ts_service_provider' => 'IPTV',
                'pcr_period_ms' => 20,
                'pat_period_ms' => 100,
                'pmt_period_ms' => 100,
                'muxrate_k' => 6000,
            ],
            [
                'name' => 'LIVE 720p (Low CPU)',
                'type' => 'h264_cpu',
                'mode' => 'live',
                'description' => 'LIVE 720p ultra-fast encoding for low-end hardware',
                'width' => 1280,
                'height' => 720,
                'fps_mode' => 'cfr',
                'fps' => 25,
                'video_bitrate_k' => 2000,
                'maxrate_k' => 2000,
                'bufsize_k' => 4000,
                'crf' => null,
                'preset' => 'superfast',
                'profile' => 'main',
                'pix_fmt' => 'yuv420p',
                'gop' => 50,
                'audio_codec' => 'aac',
                'audio_bitrate_k' => 128,
                'audio_channels' => 2,
                'container' => 'mpegts',
                'extra_ffmpeg' => '-ar 48000 -mpegts_flags +resend_headers',
                'is_system' => true,
                'ts_service_name' => 'LIVE 720p LowCPU',
                'ts_service_provider' => 'IPTV',
                'pcr_period_ms' => 20,
                'pat_period_ms' => 100,
                'pmt_period_ms' => 100,
                'muxrate_k' => 2500,
            ],
        ];

        foreach ($profiles as $profile) {
            EncodeProfile::firstOrCreate(
                ['name' => $profile['name']],
                $profile
            );
        }
    }
}
